# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_ui.ui'
#
# Created: Sun Sep 23 12:11:18 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(731, 599)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mapFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapFrame.sizePolicy().hasHeightForWidth())
        self.mapFrame.setSizePolicy(sizePolicy)
        self.mapFrame.setFrameShape(QtGui.QFrame.Box)
        self.mapFrame.setObjectName(_fromUtf8("mapFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.mapFrame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.middleVerticalLayout = QtGui.QVBoxLayout()
        self.middleVerticalLayout.setObjectName(_fromUtf8("middleVerticalLayout"))
        self.horizontalLayout.addLayout(self.middleVerticalLayout)
        self.gridLayout.addWidget(self.mapFrame, 5, 0, 1, 3)
        self.informationGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.informationGroupBox.sizePolicy().hasHeightForWidth())
        self.informationGroupBox.setSizePolicy(sizePolicy)
        self.informationGroupBox.setMaximumSize(QtCore.QSize(431, 122))
        self.informationGroupBox.setObjectName(_fromUtf8("informationGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.informationGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.longitudeLabel = QtGui.QLabel(self.informationGroupBox)
        self.longitudeLabel.setText(_fromUtf8(""))
        self.longitudeLabel.setObjectName(_fromUtf8("longitudeLabel"))
        self.gridLayout_3.addWidget(self.longitudeLabel, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.informationGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.regionLabel = QtGui.QLabel(self.informationGroupBox)
        self.regionLabel.setText(_fromUtf8(""))
        self.regionLabel.setObjectName(_fromUtf8("regionLabel"))
        self.gridLayout_3.addWidget(self.regionLabel, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.informationGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.informationGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.informationGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.latitudeLabel = QtGui.QLabel(self.informationGroupBox)
        self.latitudeLabel.setText(_fromUtf8(""))
        self.latitudeLabel.setObjectName(_fromUtf8("latitudeLabel"))
        self.gridLayout_3.addWidget(self.latitudeLabel, 4, 1, 1, 1)
        self.cityLabel = QtGui.QLabel(self.informationGroupBox)
        self.cityLabel.setText(_fromUtf8(""))
        self.cityLabel.setObjectName(_fromUtf8("cityLabel"))
        self.gridLayout_3.addWidget(self.cityLabel, 1, 1, 1, 1)
        self.countryLabel = QtGui.QLabel(self.informationGroupBox)
        self.countryLabel.setText(_fromUtf8(""))
        self.countryLabel.setObjectName(_fromUtf8("countryLabel"))
        self.gridLayout_3.addWidget(self.countryLabel, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.informationGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.informationGroupBox, 1, 0, 1, 2)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.ipLineEdit = QtGui.QLineEdit(self.frame)
        self.ipLineEdit.setObjectName(_fromUtf8("ipLineEdit"))
        self.horizontalLayout_2.addWidget(self.ipLineEdit)
        self.searchButton = QtGui.QPushButton(self.frame)
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.horizontalLayout_2.addWidget(self.searchButton)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ipLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.searchButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.informationGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "IP Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "City:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Country:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Region:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "IP Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.ipLineEdit.setText(QtGui.QApplication.translate("MainWindow", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

